package com.gynda.fridaystm.ui.theme

import androidx.compose.ui.graphics.Color

/** Forest green identity with warm neutral surfaces and semantic status colors. */
val PrimaryLight = Color(0xFF146C50)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD9F2E5)
val OnPrimaryContainerLight = Color(0xFF103D2D)
val SecondaryLight = Color(0xFF446653)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE0EEE4)
val OnSecondaryContainerLight = Color(0xFF213D2C)
val TertiaryLight = Color(0xFF825500)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFE9BD)
val OnTertiaryContainerLight = Color(0xFF513800)
val BackgroundLight = Color(0xFFF5F7F4)
val OnBackgroundLight = Color(0xFF17231C)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF17231C)
val SurfaceVariantLight = Color(0xFFEAF0EA)
val OnSurfaceVariantLight = Color(0xFF536157)
val OutlineLight = Color(0xFF78877C)
val OutlineVariantLight = Color(0xFFD8E1D9)
val SurfaceContainerLowLight = Color(0xFFF8FAF7)
val SurfaceContainerLight = Color(0xFFF0F4EF)
val SurfaceContainerHighLight = Color(0xFFEAF0E9)
val ErrorLight = Color(0xFFAE3034)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFE4E2)
val OnErrorContainerLight = Color(0xFF6B181C)

val PrimaryDark = Color(0xFF92D6B4)
val OnPrimaryDark = Color(0xFF083B27)
val PrimaryContainerDark = Color(0xFF21513B)
val OnPrimaryContainerDark = Color(0xFFD5F5E1)
val SecondaryDark = Color(0xFFB0CDB9)
val OnSecondaryDark = Color(0xFF1E3527)
val SecondaryContainerDark = Color(0xFF334C3D)
val OnSecondaryContainerDark = Color(0xFFDCEEE1)
val TertiaryDark = Color(0xFFEAC477)
val OnTertiaryDark = Color(0xFF432D00)
val TertiaryContainerDark = Color(0xFF624716)
val OnTertiaryContainerDark = Color(0xFFFFE6B0)
val BackgroundDark = Color(0xFF101A14)
val OnBackgroundDark = Color(0xFFE4EDE5)
val SurfaceDark = Color(0xFF16211A)
val OnSurfaceDark = Color(0xFFE4EDE5)
val SurfaceVariantDark = Color(0xFF29372D)
val OnSurfaceVariantDark = Color(0xFFB5C4B8)
val OutlineDark = Color(0xFF849689)
val OutlineVariantDark = Color(0xFF36473C)
val SurfaceContainerLowDark = Color(0xFF19271E)
val SurfaceContainerDark = Color(0xFF1E2D23)
val SurfaceContainerHighDark = Color(0xFF29372D)
val ErrorDark = Color(0xFFFFB4AE)
val OnErrorDark = Color(0xFF5F1519)
val ErrorContainerDark = Color(0xFF7D2428)
val OnErrorContainerDark = Color(0xFFFFDAD7)
